import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://app.powerbi.com/singleSignOn?experience=power-bi&ru=https%3A%2F%2Fapp.powerbi.com%2Fgroups%2Fme%2Freports%2F6a910f57-fbf5-45f2-8064-bf2463667097%2Fbfd774259b1360b0e2a0%3Fexperience%3Dpower-bi%26noSignUpCheck%3D1")
    page.get_by_role("textbox", name="Enter email").click()
    page.get_by_role("textbox", name="Enter email").fill("comercial.powerbi@jcatlm.com.br")
    page.get_by_role("textbox", name="Enter email").press("Enter")
    page.get_by_role("textbox", name="Insira a senha para comercial").click()
    page.get_by_role("textbox", name="Insira a senha para comercial").fill("jca@2026")
    page.get_by_role("button", name="Entrar").click()
    page.locator("#lightbox").click()
    page.get_by_role("button", name="Não").click()
    page.get_by_role("button", name="Limpar seleções").click()
    page.get_by_role("button", name="Limpar seleções").click()
    page.get_by_role("combobox", name="Semana do Ano").locator("i").click()
    page.locator("div:nth-child(3) > .slicerItemContainer > .slicerCheckbox > .glyphicon").click(modifiers=["ControlOrMeta"])
    page.locator("div:nth-child(4) > .slicerItemContainer > .slicerCheckbox > .glyphicon").click(modifiers=["ControlOrMeta"])
    page.locator("div:nth-child(4) > .slicerItemContainer > .slicerCheckbox > .glyphicon").click(modifiers=["ControlOrMeta"])
    page.locator("div:nth-child(4) > .slicerItemContainer > .slicerCheckbox > .glyphicon").click(modifiers=["ControlOrMeta"])
    page.locator("div:nth-child(5) > .slicerItemContainer > .slicerCheckbox > .glyphicon").click(modifiers=["ControlOrMeta"])
    page.locator("div:nth-child(6) > .slicerItemContainer > .slicerCheckbox > .glyphicon").click(modifiers=["ControlOrMeta"])
    page.locator(".dropdown-chevron.powervisuals-glyph.chevron-down").click()
    page.get_by_text("SAO PAULO - RIO DE JANEIRO").click()
    page.get_by_test_id("appbar-export-options-btn").click()
    page.get_by_test_id("export-to-powerPoint-btn").click()
    page.get_by_test_id("tri-dropdown").click()
    page.get_by_text("Exportar como imagem").click()
    page.get_by_text("Exportar somente a página").click()
    with page.expect_download() as download_info:
        page.get_by_test_id("dailog-ok-btn").click()
    download = download_info.value
    page.locator("div:nth-child(7) > .vcBody > .visualWrapper > visual-modern > .visual > .slicer-container > .slicer-content-wrapper > .slicer-dropdown-menu > .dropdown-chevron").click()
    page.get_by_text("SAO PAULO - BELO HORIZONTE").click()
    page.get_by_test_id("appbar-export-options-btn").click()
    page.get_by_test_id("export-to-powerPoint-btn").click()
    page.get_by_test_id("tri-dropdown").click()
    page.get_by_text("Exportar como imagem").click()
    page.get_by_text("Exportar somente a página").click()
    with page.expect_download() as download1_info:
        page.get_by_test_id("dailog-ok-btn").click()
    download1 = download1_info.value
    page.get_by_test_id("visual-container-repeat").get_by_text("SAO PAULO - BELO HORIZONTE").click()
    page.get_by_text("BELO HORIZONTE - RIO DE").click()
    page.get_by_test_id("appbar-export-options-btn").click()
    page.get_by_test_id("export-to-powerPoint-btn").click()
    page.get_by_test_id("tri-dropdown").click()
    page.get_by_text("Exportar como imagem").click()
    page.get_by_text("Exportar somente a página").click()
    with page.expect_download() as download2_info:
        page.get_by_test_id("dailog-ok-btn").click()
    download2 = download2_info.value
    page.get_by_role("combobox", name="Semana do Ano").locator("i").click()
    page.get_by_role("option", name="1").press("ArrowDown")
    page.get_by_role("option", name="2").press("ArrowDown")
    page.get_by_role("option", name="3").press("ArrowDown")
    page.get_by_role("option", name="4").press("ArrowDown")
    page.get_by_role("option", name="5").press("ArrowDown")
    page.get_by_role("option", name="6").press("ArrowDown")
    page.get_by_role("option", name="7").press("ArrowDown")
    page.get_by_role("option", name="8").press("ArrowDown")
    page.get_by_role("option", name="9").press("ArrowDown")
    page.get_by_role("option", name="10").press("ArrowDown")
    page.get_by_role("option", name="11").press("ArrowDown")
    page.get_by_role("option", name="12").press("ArrowDown")
    page.get_by_role("option", name="13").press("ArrowDown")
    page.get_by_role("option", name="14").press("ArrowDown")
    page.get_by_role("option", name="15").press("ArrowDown")
    page.get_by_role("option", name="16").press("ArrowDown")
    page.get_by_role("option", name="17").press("ArrowDown")
    page.get_by_role("option", name="18").press("ArrowUp")
    page.get_by_role("option", name="17").press("ControlOrMeta+Enter")
    page.locator("tri-link").filter(has_text="Mostrar os atalhos de teclado").press("Escape")
    page.get_by_text("Seleções múltiplas").click()
    page.get_by_role("option", name="1").press("ArrowDown")
    page.get_by_role("option", name="2").press("ControlOrMeta+ ")
    page.get_by_role("option", name="2").press("ControlOrMeta+ArrowDown")
    page.get_by_role("option", name="3").press("ControlOrMeta+ ")
    page.get_by_role("option", name="3").press("ControlOrMeta+ArrowDown")
    page.get_by_role("option", name="4").press("ControlOrMeta+ ")
    page.get_by_role("option", name="4").press("ControlOrMeta+ArrowDown")
    page.get_by_role("option", name="5").press("ControlOrMeta+ ")

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
